image: node:latest
stages:
  - install
  - deploy

install:
  stage: install
  script:
    - npm install

deploy:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
