image: node:latest
stages:
  - deploy
before_script:
  - npm install -g typescript

deploy:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
