image: node:latest
stages:
  - deploy
before_script:
  - npm pack file:chewy-lib
  - npm install

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
